require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CoffeeIntakesController do

  # This should return the minimal set of attributes required to create a valid
  # CoffeeIntake. As you add validations to CoffeeIntake, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "user_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CoffeeIntakesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all coffee_intakes as @coffee_intakes" do
      coffee_intake = CoffeeIntake.create! valid_attributes
      get :index, {}, valid_session
      assigns(:coffee_intakes).should eq([coffee_intake])
    end
  end

  describe "GET show" do
    it "assigns the requested coffee_intake as @coffee_intake" do
      coffee_intake = CoffeeIntake.create! valid_attributes
      get :show, {:id => coffee_intake.to_param}, valid_session
      assigns(:coffee_intake).should eq(coffee_intake)
    end
  end

  describe "GET new" do
    it "assigns a new coffee_intake as @coffee_intake" do
      get :new, {}, valid_session
      assigns(:coffee_intake).should be_a_new(CoffeeIntake)
    end
  end

  describe "GET edit" do
    it "assigns the requested coffee_intake as @coffee_intake" do
      coffee_intake = CoffeeIntake.create! valid_attributes
      get :edit, {:id => coffee_intake.to_param}, valid_session
      assigns(:coffee_intake).should eq(coffee_intake)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new CoffeeIntake" do
        expect {
          post :create, {:coffee_intake => valid_attributes}, valid_session
        }.to change(CoffeeIntake, :count).by(1)
      end

      it "assigns a newly created coffee_intake as @coffee_intake" do
        post :create, {:coffee_intake => valid_attributes}, valid_session
        assigns(:coffee_intake).should be_a(CoffeeIntake)
        assigns(:coffee_intake).should be_persisted
      end

      it "redirects to the created coffee_intake" do
        post :create, {:coffee_intake => valid_attributes}, valid_session
        response.should redirect_to(CoffeeIntake.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved coffee_intake as @coffee_intake" do
        # Trigger the behavior that occurs when invalid params are submitted
        CoffeeIntake.any_instance.stub(:save).and_return(false)
        post :create, {:coffee_intake => { "user_id" => "invalid value" }}, valid_session
        assigns(:coffee_intake).should be_a_new(CoffeeIntake)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        CoffeeIntake.any_instance.stub(:save).and_return(false)
        post :create, {:coffee_intake => { "user_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested coffee_intake" do
        coffee_intake = CoffeeIntake.create! valid_attributes
        # Assuming there are no other coffee_intakes in the database, this
        # specifies that the CoffeeIntake created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        CoffeeIntake.any_instance.should_receive(:update_attributes).with({ "user_id" => "1" })
        put :update, {:id => coffee_intake.to_param, :coffee_intake => { "user_id" => "1" }}, valid_session
      end

      it "assigns the requested coffee_intake as @coffee_intake" do
        coffee_intake = CoffeeIntake.create! valid_attributes
        put :update, {:id => coffee_intake.to_param, :coffee_intake => valid_attributes}, valid_session
        assigns(:coffee_intake).should eq(coffee_intake)
      end

      it "redirects to the coffee_intake" do
        coffee_intake = CoffeeIntake.create! valid_attributes
        put :update, {:id => coffee_intake.to_param, :coffee_intake => valid_attributes}, valid_session
        response.should redirect_to(coffee_intake)
      end
    end

    describe "with invalid params" do
      it "assigns the coffee_intake as @coffee_intake" do
        coffee_intake = CoffeeIntake.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CoffeeIntake.any_instance.stub(:save).and_return(false)
        put :update, {:id => coffee_intake.to_param, :coffee_intake => { "user_id" => "invalid value" }}, valid_session
        assigns(:coffee_intake).should eq(coffee_intake)
      end

      it "re-renders the 'edit' template" do
        coffee_intake = CoffeeIntake.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CoffeeIntake.any_instance.stub(:save).and_return(false)
        put :update, {:id => coffee_intake.to_param, :coffee_intake => { "user_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested coffee_intake" do
      coffee_intake = CoffeeIntake.create! valid_attributes
      expect {
        delete :destroy, {:id => coffee_intake.to_param}, valid_session
      }.to change(CoffeeIntake, :count).by(-1)
    end

    it "redirects to the coffee_intakes list" do
      coffee_intake = CoffeeIntake.create! valid_attributes
      delete :destroy, {:id => coffee_intake.to_param}, valid_session
      response.should redirect_to(coffee_intakes_url)
    end
  end

end
